version: 0.9.{build}
branches:
  only:
  - master
clone_folder: c:\projects\cmake-init
image:
- Visual Studio 2017
configuration:
- Release
platform:
- x64
environment:
  matrix:
  - arch: Win64
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- echo %generator%

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator% -DCAPSTONE_BUILD_SHARED=0 -DCAPSTONE_BUILD_TESTS=0 -DCAPSTONE_BUILD_CSTOOL=0
build:
  project: c:\projects\cmake-init\build\WoWOffsetDumper.sln
  verbosity: minimal
  parallel: true
only_commits:
  files:
    - CMakeLists.txt
	- CMakeSettings.json
    - appveyor.yml
	- cmake/
	- deps/
    - src/